### ISSUE TITLE
Overwrite TIGER/Line legislative districts that have been updated by courts

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates-district-maps#2]
- [ ] Florida

@jamesturk, any others? I have faint memories of GA, NC, and VA, but while I can find court cases, I can't find any outcomes.

New TIGER/Line data will be released in mid-August, and would hopefully fix these.

**Comment by mileswwatkins** [comment]
Right now, we're using the 2014 Census GEOIDs, which _may_ miss some changes/districts? At some point I should re-run the CSV generation script in the OCD-division-IDs repo.

**Comment by jamesturk** [comment]
FL is the only one I know that has new lines that have had an election already

**Comment by mileswwatkins** [comment]
Looks like we're good here already, but I'll bump the TIGER/Line vintage form 2016 to 2017 for good measure.
